# backend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: localhost:5000/dicom-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5001
        - containerPort: 11119  # Add this line to expose the DICOM port
        env:
        - name: PACS_IP
          value: "pacs-service"    # The name of the PACS service in K8s
        - name: PACS_PORT
          value: "104"
        - name: PACS_AE_TITLE
          value: "MYPACS"
        - name: CLIENT_AE_TITLE
          value: "TESTSCU2"
        - name: CLIENT_PORT
          value: "11119"
        - name: BACKEND_PORT
          value: "5001"
        

---
apiVersion: v1
kind: Service
metadata:
  name: dicom-backend-service
spec:
  selector:
    app: backend    # Changed from 'dicom-backend' to match Deployment labels
  ports:
  - name: http
    protocol: TCP
    port: 5001
    targetPort: 5001
  - name: dicom-cstore
    port: 11119
    targetPort: 11119
  type: ClusterIP
