apiVersion: v1
kind: Service
metadata:
  name: hammurabi-ui-service
spec:
  type: ClusterIP
  selector:
    app: hammurabi-ui
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http-3000
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http-80
