apiVersion: v1
kind: Pod
metadata:
  name: aws-cli-test
  namespace: kube-system
spec:
  serviceAccountName: aws-load-balancer-controller
  containers:
  - name: aws-cli
    image: amazon/aws-cli
    command: [ "sh", "-c", "aws sts get-caller-identity || true; sleep 3600" ]
