# .github/workflows/ci-cd.yml
name: CI‑CD
on:
  push:    { branches: [ main ] }
  pull_request: { branches: [ main ] }

env:
  AWS_REGION:      ${{ secrets.AWS_REGION }}
  ECR_REPO:        ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/hammurabi-ui-prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: CI         # secrets scope
    permissions:
      id-token: write
      contents: read

    steps:
    - uses: actions/checkout@v4

    # ---- AWS creds (OIDC)
    - uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ secrets.GH_OIDC_ROLE_ARN }}
        aws-region:     ${{ env.AWS_REGION }}

    - uses: aws-actions/amazon-ecr-login@v1

    # ---- Build & push immagine
    - name: Build & push Docker
      id: build
      run: |
        TAG=$(git rev-parse --short HEAD)
        docker build -t $ECR_REPO:$TAG --build-arg VERSION_INFO=$TAG Hammurabi/hammurabi-ui
        docker push $ECR_REPO:$TAG
        echo "tag=$TAG" >> $GITHUB_OUTPUT

    # ---- Toolchain
    - uses: actions/setup-node@v4
      with: { node-version: 20 }
    - run: npm install -g aws-cdk@2
    - run: pip3 install -r hammurabi-cdk/requirements.txt

    # ---- Scrivi google_secrets.json in situ
    - name: Inject Google OAuth secrets
      run: |
        cat > hammurabi-cdk/react_ecs_complete_cdk/google_secrets.json <<'EOF'
        {
          "web": {
            "client_id":    "${{ secrets.GOOGLE_CLIENT_ID }}",
            "client_secret":"${{ secrets.GOOGLE_CLIENT_SECRET }}"
          }
        }
        EOF

    # ---- Deploy CDK
    - name: CDK deploy Blue/Green
      run: |
        cd hammurabi-cdk
        cdk deploy ReactCdkCompleteStack \
          -c imageTag=${{ steps.build.outputs.tag }} \
          --require-approval never
