name: CI‑CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AWS_REGION: us-east-1
  ECR_REPO: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/hammurabi-ui-prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.GH_OIDC_ROLE_ARN }}
          aws-region: us-east-1

      - uses: aws-actions/amazon-ecr-login@v1

      - name: Build & push Docker
        id: build
        run: |
          TAG=$(git rev-parse --short HEAD)
          docker build -t $ECR_REPO:$TAG --build-arg VERSION_INFO=$TAG Hammurabi/hammurabi-ui
          docker push $ECR_REPO:$TAG
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: CDK deploy Blue/Green
        run: |
          cd hammurabi-cdk
          cdk deploy ReactCdkCompleteStack -c imageTag=${{ steps.build.outputs.tag }} --require-approval never

