name: CI‑CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_REPO: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/hammurabi-ui-prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: CI
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      # —―― install AWS credentials (OIDC)
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.GH_OIDC_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - uses: aws-actions/amazon-ecr-login@v1

      # —―― build/push immagine
      - name: Build & push Docker
        id: build
        run: |
          TAG=$(git rev-parse --short HEAD)
          docker build -t $ECR_REPO:$TAG --build-arg VERSION_INFO=$TAG Hammurabi/hammurabi-ui
          docker push $ECR_REPO:$TAG
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      # —―― install Node + CDK CLI + dipendenze Python
      - name: Install CDK toolchain
        run: |
          # Node (necessario al CLI)
          sudo apt-get update -y
          sudo apt-get install -y python3-pip  # assicura pip
        # oppure usa l’action:
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install CDK CLI
        run: npm install -g aws-cdk@2

      - name: Install Python deps
        run: pip3 install -r hammurabi-cdk/requirements.txt

      # —―― cdk deploy
      - name: CDK deploy Blue/Green
        run: |
          cd hammurabi-cdk
          cdk deploy ReactCdkCompleteStack \
            -c imageTag=${{ steps.build.outputs.tag }} \
            --require-approval never
